spring.application.name=ms-pago
server.port=8009

spring.datasource.url=jdbc:mariadb://localhost:3306/pago_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.flyway.enabled=true
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration

logging.level.root=INFO
logging.level.com.ticketuki=DEBUG

ms.venta.url=${MS_VENTA_URL:http://localhost:8006}
ms.usuario.url=${MS_USUARIO_URL:http://localhost:8001}
ms.ticket.url=${MS_TICKET_URL:http://localhost:8005}
ms.estado.url=${MS_ESTADO_URL:http://localhost:8004}
