spring.application.name=ms-recinto
server.port=8008

spring.datasource.url=jdbc:mariadb://localhost:3306/recinto_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.flyway.enabled=true
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration

logging.level.root=INFO
logging.level.com.ticketuki=DEBUG
