spring.application.name=estado-service
server.port=8004

spring.datasource.url=jdbc:mariadb://localhost:3306/estado_service
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration

logging.level.root=INFO
logging.level.com.ticketuki.estadoservice=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
